Changing rendering
JonasPfeifer05/rui pull request #2
Opened 2022-10-07 13:33 UTC by ToBinio

changing rendering so that the render_pass can be reused

2022-10-07 19:53 UTC, JonasPfeifer05 requested changes

2022-10-07 19:53 UTC, JonasPfeifer05 commented on src/shapes.rs
> +    fn update_vertex_buffer(&mut self, device: &Device) {
So on each draw call the buffer should be created completely new?

2022-10-07 19:53 UTC, JonasPfeifer05 commented
Why is that so?

2022-10-08 07:12 UTC, ToBinio commented
after now removing the update handleling in the draw function i wondert if it is nessary to have an update function delcated in the trait. over all it is currently not need in the trait but it probaly is a good reminder to have it in there so you dont forget that you need to update the buffers... what are your thoughts?

2022-10-08 09:23 UTC, JonasPfeifer05 commented
Yea I think we could split it up in something like a StaticComponent/shape and DynamicComponent/shape if we later need to update the buffers. But now we dont need it

2022-10-08 09:23 UTC, merged